[package]
name = "exporter"
version = "0.1.0"
authors = ["Nathan Adams <dinnerbone@dinnerbone.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]
clap = "3.0.0-beta.2"
ruffle_core = { path = "../core" }
ruffle_render_wgpu = { path = "../render/wgpu", features = ["clap"] }
env_logger = "0.9.0"
image = "0.23.14"
log = "0.4"
futures = "0.3.15"
path-slash = "0.1.4"
walkdir = "2.3.2"
indicatif = "0.16"

[features]
avm_debug = ["ruffle_core/avm_debug"]
render_debug_labels = ["ruffle_render_wgpu/render_debug_labels"]
render_trace = ["ruffle_render_wgpu/render_trace"]
lzma = ["ruffle_core/lzma"]
