[package]
name = "ruffle_video_external"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
ruffle_render = { path = "../../render" }
ruffle_video = { path = ".." }
swf = { path = "../../swf" }
slotmap = { workspace = true }
tracing = { workspace = true }
ruffle_video_software = { path = "../software" }

# Needed for OpenH264:
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
libloading = "0.8.3"
md-5 = "0.10.6"
reqwest = { version = "0.12.3", default-features = false, features = ["blocking"] }
hex = "0.4.3"
bzip2 = { version = "0.4.4", features = ["static"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
web-sys = { version = "0.3.69", features = [
    "VideoDecoder", "VideoDecoderConfig", "VideoDecoderInit", "EncodedVideoChunk", "EncodedVideoChunkInit",
    "EncodedVideoChunkType", "DomException", "CodecState"
]}
js-sys = { workspace = true }
wasm-bindgen = { workspace = true }

[package.metadata.cargo-machete]
ignored = [
    # Renames itself to "md5", see: https://github.com/bnjbvr/cargo-machete/issues/8
    "md-5"
]
