name: Release to addons.mozilla.org

on:
  # Run weekly every Friday
  schedule:
   - cron: "0 2 * * 6"

  # Allow for manual releases if needed
  workflow_dispatch:

jobs:
  submit-amo:
    name: Submit to addons.mozilla.org
    runs-on: ubuntu-22.04

    steps:
      - name: Get latest release tag and date
        id: release_info
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: "ruffle-rs/ruffle"
        # NOTE: The following line relies on the output of the `gh` command (when piped) looking like this:
        # "Nightly 2024-04-20      Pre-release     nightly-2024-04-20      2024-04-20T00:03:23Z"
        # And sets the following outputs: date = "2024_04_20", tag = "nightly-2024-04-20"
        # NOTE: The hyphens in the date are replaced with underscores.
        run: gh release list -L1 | awk '{ print "tag="$4; gsub(/-/, "_"); print "date="$2; }' >> "$GITHUB_OUTPUT"

      - uses: actions/checkout@v4
        with:
          ref: ${{ steps.release_info.outputs.tag }}

      - name: Install node packages
        working-directory: web
        shell: bash -l {0}
        run: npm ci

      - name: Download latest release assets
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: "ruffle-rs/ruffle"
          RELEASE_TAG: ${{ steps.release_info.outputs.tag }}
          RELEASE_DATE: ${{ steps.release_info.outputs.date }}
        run: |

          echo "only"
          echo "'"${RELEASE_TAG}"'"
          echo "'"${RELEASE_DATE}"'"

      - name: Publish Firefox extension
        id: sign-firefox
        continue-on-error: true
        env:
          SOURCE_TAG: ${{ steps.release_info.outputs.tag }}
        working-directory: web/packages/extension
        shell: bash -l {0}
        run: |
          echo "only"
          echo "'"${SOURCE_TAG}"'"

          npm run sign-firefox

