[package]
name = "ruffle_desktop"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
clap = { version = "4.4.6", features = ["derive"] }
cpal = "0.15.2"
egui = { workspace = true }
egui-wgpu = { version = "0.23.0", features = ["winit"] }
egui-winit = "0.23.0"
fontdb = "0.15"
ruffle_core = { path = "../core", features = ["audio", "clap", "mp3", "nellymoser", "default_compatibility_rules", "egui", "default_font"] }
ruffle_render = { path = "../render", features = ["clap"] }
ruffle_render_wgpu = { path = "../render/wgpu", features = ["clap"] }
ruffle_video_software = { path = "../video/software", optional = true }
tracing = { workspace = true}
tracing-subscriber = { workspace = true }
generational-arena = "0.2.9"
winit = "0.29.1-beta"
webbrowser = "0.8.12"
url = "2.4.1"
arboard = "3.2.1"
dirs = "5.0"
isahc = { version = "1.7.2", features = ["cookies"] }
rfd = "0.12.1"
anyhow = "1.0"
bytemuck = "1.14.0"
os_info = { version = "3", default-features = false }
unic-langid = "0.9.1"
sys-locale = "0.3.1"
wgpu = { workspace = true }
futures = "0.3.28"
chrono = { version = "0.4", default-features = false, features = [] }
fluent-templates = "0.8.0"
futures-lite = "1.13.0"
async-io = "2.0.0"
async-net = "1.8.0"
async-channel = "1.9.0"

# Deliberately held back to match tracy client used by profiling crate
tracing-tracy = { version = "=0.10.2", optional = true }

[target.'cfg(windows)'.dependencies]
winapi = "0.3.9"

[build-dependencies]
embed-resource = "2"
vergen = { version = "8.2.5", features = ["build", "git", "gitcl", "cargo"] }

[features]
default = ["software_video"]
jpegxr = ["ruffle_core/jpegxr"]

# core features
avm_debug = ["ruffle_core/avm_debug"]
lzma = ["ruffle_core/lzma"]
software_video = ["ruffle_video_software"]
tracy = ["tracing-tracy", "ruffle_render_wgpu/profile-with-tracy"]

# wgpu features
render_debug_labels = ["ruffle_render_wgpu/render_debug_labels"]
render_trace = ["ruffle_render_wgpu/render_trace"]

# sandboxing
sandbox = []
