[package]
name = "ruffle_desktop"
version = "0.1.0"
authors = ["Ruffle LLC <ruffle@ruffle.rs>"]
edition = "2021"
default-run = "ruffle_desktop"
license = "MIT OR Apache-2.0"

[dependencies]
clap = { version = "3.2.20", features = ["derive"] }
cpal = "0.14.0"
ruffle_core = { path = "../core", features = ["audio", "symphonia", "nellymoser"] }
ruffle_render_wgpu = { path = "../render/wgpu", features = ["clap"] }
ruffle_video_software = { path = "../video/software", optional = true }
env_logger = { version = "0.9", default-features = false, features = ["humantime"] }
generational-arena = "0.2.8"
log = "0.4"
winit = "0.27.3"
webbrowser = "0.8.0"
url = "2.3.1"
clipboard = "0.5.0"
dirs = "4.0"
isahc = "1.7.2"
rfd = "0.10.0"
anyhow = "1.0"

egui = "0.19.0"

egui-wgpu = { version = "0.19", features = [ "winit" ] }
egui-winit = { version = "0.19", default-features = false }
egui_demo_lib = "0.19"

wgpu = "0.13.0"

[target.'cfg(windows)'.dependencies]
winapi = "0.3.9"

[build-dependencies]
embed-resource = "1"

[features]
default = ["software_video"]

# core features
avm_debug = ["ruffle_core/avm_debug"]
lzma = ["ruffle_core/lzma"]
software_video = ["ruffle_video_software"]

# wgpu features
render_debug_labels = ["ruffle_render_wgpu/render_debug_labels"]
render_trace = ["ruffle_render_wgpu/render_trace"]

# sandboxing
sandbox = []